version: "3"
services:
  server:
    image: "amsimpson/mac-webpagetest-server"
    ports:
        - "4000:80"
  agent:
    image: "webpagetest/agent"
    environment:
      SERVER_URL: "http://localhost:4000/work/"
      LOCATION: "Test"
      SHAPER: "none"
    network_mode: "host"
    extra_hosts:
      - "foo.dev:192.168.x.xxx"
